### ISSUE TITLE
New functionality request

### ISSUE THREAD

**Issue by brusarp** [ryanrwatkins/Google-Sheet-to-Calendar#2]
I managed to implement your script in my sheet and calendar.
It works if the rows are defined and always the same ones.
In case I wanted to continue updating the sheet, how can I do it?
Example:
If I put the range A7:E50 because I plan to use 44 events (but not right away! Over the next few months I will add one or two events per week) it gives me the error "The parameters (String,String,String,(class)) don't match the method signature for CalendarApp.Calendar.createEvent. CreateEvent".
How can I do it?
Maybe even by selecting only the events I want to load (could that be an idea?)
EDIT: or, if the "title" is empty, don't attempt to sync

Thank you

**Comment by ryanrwatkins** [comment]
Thanks for the note. That is odd since I have mine set to include several empty rows and I don't get the error.  Here is what ChatGPT suggested: 
To fix this, you can modify your code to check for valid data before trying to create an event. Here's an updated version of your code that includes a check to ensure that both the start and end dates are valid before creating the event:

`function FunctionGWcodersSchedule() {
  
  // Get the spreadsheet and sheet/tab within, then get the calendar ID from the spreadsheet, and get the calendar
  var spreadsheet = SpreadsheetApp.openByUrl("SHEET ID").getSheetByName("schedule");
  var calendarId = spreadsheet.getRange("A2").getValue();
  var eventCal = CalendarApp.getCalendarById(calendarId);
  
  var topics = spreadsheet.getRange("A7:E50").getValues();  //Get the section of the spreadsheet we are using
  
  // Delete all the events in the calendar from the specified date range
  var fromDate = new Date(2023, 0, 1); // January 1, 2023
  var toDate = new Date(2025, 6, 1);   // June 1, 2025
  
  var events = eventCal.getEvents(fromDate, toDate);   //Get all events in the time range

  for (var i = 0; i < events.length; i++) {  
    var ev = events[i];   
    ev.deleteEvent();     // delete the event
  }
  
  // Create new events only if valid data is present
  for (var x = 0; x < topics.length; x++) {
    var meetup = topics[x];   // Get each row from the sheet
    
    var begin = new Date(meetup[0]);    // Get start time
    var end = new Date(meetup[1]);      // Get end time
    var topic = meetup[2];              // Get event topic
    var description = meetup[3];        // Get description
    var presenter = meetup[4];          // Get presenter

    // Check if all necessary fields have valid data
    if (!isNaN(begin.getTime()) && !isNaN(end.getTime()) && topic && presenter) {
      // Create the event
      eventCal.createEvent("GW Coders: " + topic + ' with ' + presenter, begin, end, {
        location: 'SEH 2600 or Zoom'
      }).addPopupReminder(30).setDescription(description);
      
      // Pause briefly since you can only edit the calendar so many times per second
      Utilities.sleep(2000);
    }
  }
}`

Key Changes:
Validation of Date and Content: The script now checks whether the begin, end, topic, and presenter variables contain valid data before creating an event. Specifically, isNaN(begin.getTime()) and isNaN(end.getTime()) ensure that the begin and end values are valid dates.

Skipping Empty Rows: If a row is empty or has incomplete data, the script will skip that row and not attempt to create an event for it.

If it works for you, please do a pull request with the improved code and I will accept it as an update.  Since mine is already working I won't know if it fixes this issue.  Thanks!

**Comment by brusarp** [comment]
Thank you for such a quick response!
I don't know if it's an oversight but I think you should remove the reference to the sheet

**Comment by ryanrwatkins** [comment]
Good catch, I was moving too quickly before having enough coffee. THANKS.

**Comment by brusarp** [comment]
No problem 😉
Anyway, the modification seems to work well, I try to prepare the PR 👍🏻

**Comment by ryanrwatkins** [comment]
Wonderful, it is now updated for others. Thanks!
